version: '2'
services:
    soapy-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/soapy/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=soapy
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
